package RpgGame;

 public class Character {                                                                                                                                                                                         
                                                                                                                                                                                                                     
        private String name;                                                                                                                                                                                         
        private int level;                                                                                                                                                                                           
        private int life;                                                                                                                                                                                            
        private int strength;                                                                                                                                                                                        
                                                                                                                                                                                                                     
        // Constructor                                                                                                                                                                                               
        public Character(String name) {                                                                                                                                                                              
            this.setName(name);                                                                                                                                                                                      
            this.setLevel(1);                                                                                                                                                                                        
            this.setLife(100);                                                                                                                                                                                       
            this.setStrength(50);                                                                                                                                                                                    
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        // Getters and Setters                                                                                                                                                                                       
        public String getName() {                                                                                                                                                                                    
            return name;                                                                                                                                                                                             
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public void setName(String name) {                                                                                                                                                                           
            this.name = name;                                                                                                                                                                                        
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public int getLevel() {                                                                                                                                                                                      
            return level;                                                                                                                                                                                            
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public void setLevel(int level) {                                                                                                                                                                            
            if (level > 0) {                                                                                                                                                                                         
                this.level = level;                                                                                                                                                                                  
            }                                                                                                                                                                                                        
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public int getLife() {                                                                                                                                                                                       
            return life;                                                                                                                                                                                             
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public void setLife(int life) {                                                                                                                                                                              
            if (life >= 0) {                                                                                                                                                                                         
                this.life = life;                                                                                                                                                                                    
            }                                                                                                                                                                                                        
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public int getStrength() {                                                                                                                                                                                   
            return strength;                                                                                                                                                                                         
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        public void setStrength(int strength) {                                                                                                                                                                      
            if (strength >= 0) {                                                                                                                                                                                     
                this.strength = strength;                                                                                                                                                                            
            }                                                                                                                                                                                                        
        }                                                                                                                                                                                                            
                                                                                                                                                                                                                     
        // Method to display stats                                                                                                                                                                                   
        public void getStats() {                                                                                                                                                                                     
            System.out.println("The hero " + name + " is level " + level + " with " + life + " HP and " + strength + " strength.");                                                                                  
        }                                                                                                                                                                                                            
    }
